server:
  port: 8081

app:
  baseUrl: ${baseUrl}

spring:
  datasource:
    url: ENC(IGBIQXu1p+L0142+uplxofAcyhNyx4QBj5kJMRAByq5C/Pkr88FSy/RLM/SgafzPHUoPsuThv5CbdV9F81BylRp3CsaRs7+DKKIH3DxVldHsT7eCXyWs0suZ379EgXh7pjd34jc/VQw=)
    username: ENC(lTMVOKtY/fZl+Tug5yVIjQ==)
    password: ENC(V+/5+sksg/OG4KbxeGc84xoWdskdQPR4)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
  h2:
    console:
      enabled: false
  data:
    redis:
      host: mm-main-redis
      port: 6380
    mongodb:
      uri: ENC(znX4R1o0rUWzGfC/QYeRM+NTVM4aUe9G4YVhqk8zX0xPdvUSNIpQ0AdAJW9Pog7sL6QWaJRaJR1pKINCDKEg3AHlfnlUXbDkFuWoh3mvM6c3slnAIAIVtfaTMNjOlFweYyh9li5GklcQm5u9NBa40Na654yuOOu8)

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ENC(jtFSE8X3pgeKaeyOGatxdqrvK1t4FmdbpZaHiPf6E2RoEiEEYdOQcvD3Ko34rAH9)
            client-secret: ENC(DuxDV+plHXpQS6l4tBhROg7UthSrsjKKlKgFlQijPxeSof6VLLaZBrcK7zdTydS4)
            redirect-uri: ${redirectURL}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope: profile_nickname, profile_image, account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  access_secret: ENC(JxVNEnrDkmH9HUSpiBjDD7GvObaGAWk21JXFvZPV4FgEmUQb/9LtEwkLjtTc5Q9F+WQj/gz5vGmPiP4H4BAAgw==)
  refresh_secret: ENC(hzfWfJcKzqgetp0MJkmjjOj5t9BwEsHjTV9i/t0iili1Cihv9K4LLAPtcR3ZSF8X+Bqmw3K2yAece+I1wHfXsA==)

logging:
  level:
    root: info
websocket:
  allowedOrigins: "https://www.moodmate.site"
firebase:
  path: ENC(M47HHStR+hGcCyYNQ6hnGJ9IMadcBEmoLtXG+sYnGxs=)
